server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka